--- #YAML:1.0
name:                     Data-FormValidator-Filters-Demoroniser
version:                  0.02
abstract:                 A Data::FormValidator filter that allows you to demoronise a string.
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Text::Demoroniser:      0
recommends:
  Data::FormValidator:    0
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
build_requires:
  Test::More:             0.70

provides:
  Data::FormValidator::Filters::Demoroniser:
    file:     lib/Data/FormValidator/Filters/Demoroniser.pm
    version:  0.02
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-FormValidator-Filters-Demoroniser

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
